"""coc

Revision ID: 5586ceb43de2
Revises: 7b4ff4bc3b39
Create Date: 2021-06-07 16:01:41.646033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5586ceb43de2'
down_revision = '7b4ff4bc3b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coc')
    # ### end Alembic commands ###
