"""Flesh out profile

Revision ID: 7b4ff4bc3b39
Revises: fbd5aec040ff
Create Date: 2021-06-07 15:52:38.255721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4ff4bc3b39'
down_revision = 'fbd5aec040ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('game', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('sign_up', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('ownGame', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('host', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_column('user', 'address')
    op.drop_column('user', 'host')
    op.drop_column('user', 'ownGame')
    op.drop_column('sign_up', 'created')
    op.drop_column('game', 'updated')
    op.drop_column('game', 'created')
    # ### end Alembic commands ###
