"""make things default to false

Revision ID: a4c33c94d35d
Revises: 
Create Date: 2021-07-07 20:53:30.281669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c33c94d35d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'vaccinated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'ownGame',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'host',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'coc',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'coc',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'host',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'ownGame',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'vaccinated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
